### ISSUE TITLE
pcd2las is not working

### ISSUE THREAD

**Issue by Tejuwi** [chambbj/GeoPCL#4]
I have converted las2pcd , tested it on pcl and it is working well, I used the same file convert back to las but no display the data. any solution would be great

**Comment by chambbj** [comment]
I appreciate you giving the code a try. This repository is no longer active. As an alternative, I would recommend grabbing a copy of the PDAL library and command line application (see https://www.pdal.io for more information). Your equivalent `las2pcd` command with PDAL is

```
pdal translate input.las output.pcd
```

And back again

```
pdal translate input.pcd output.las
```

PDAL offers many options that can be set on the LAS and PCD readers and writers, along with support for nearly 100 other processing stages (readers, writers, and filters).

Closing this issue as I have no plans to update the GeoPCL codebase any further.

**Comment by Tejuwi** [comment]
Thank you your teply and sugrestions
